# Copy into a repo as .github/workflows/stale.yml
name: Stale

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: {}

jobs:
  call:
    permissions:
      issues: write
      pull-requests: write
    uses: avalon-initiative/.github/.github/workflows/stale.yml@main
